# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonovsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
