# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonovsite', '0003_auto_20170315_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='son',
            name='url',
        ),
        migrations.AddField(
            model_name='son',
            name='source_id_string',
            field=models.CharField(default='y', max_length=100),
            preserve_default=False,
        ),
    ]
