# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sonovsite', '0006_auto_20170316_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='galery',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='son',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/sonovsite/galery'),
        ),
    ]
