# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonovsite', '0007_auto_20170316_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.CharField(blank=True, max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='short_desc',
            field=models.CharField(blank=True, max_length=78, null=True),
        ),
    ]
