# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonovsite', '0008_auto_20170317_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='corpus',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='static/sonovsite/article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
